### ISSUE TITLE
Broken URL in README

### ISSUE THREAD

**Issue by manchain** [alephium/react-dapp-template#1]
Hey @polarker  I noticed that the URL in the README file is broken. The link to https://wiki.alephium.org/full-node/devnet leads to a 404 error or a non-existent page.

Steps to Reproduce:

Navigate to the README file of this repository.
Click on the link that says https://wiki.alephium.org/full-node/devnet  
Observe that it leads to a broken page or displays a 404 error.
Expected Result: The link should direct to the correct webpage/resource.

Actual Result: The link is broken and shows a 404 error or non-existent page.

Suggested Fix: Please update the URL to the correct one or remove the broken link if it is no longer valid.

Thank you!

**Comment by polarker** [comment]
Hey @nipudas29 , thanks for the issue. Just fixed it.

I will also update the template tomorrow to include meaningful contracts

**Comment by manchain** [comment]
@polarker sounds great!
